FROM node:alpine

RUN mkdir -p /usr/app && chown -R node:node /usr/app

USER node

WORKDIR /usr/app

COPY --chown=node:node package.json .

RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "start"]