version: '3'
services:
  web:
    #stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    #environment:
      #- CHOKIDAR_USEPOLLING=true
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    ports: 
      - '3000:3000'